version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/polkadot-staking-site.git
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 1200000
     runas: root
  ApplicationStart:
   - location: scripts/copy_dist
     timeout: 300
     runas: root